# =========================================================
# CONFIGURACIÓN APLICACIÓN
# =========================================================
spring.application.name=app-cloud-pedidos


# =========================================================
# CONFIGURACIÓN SERVIDOR
# =========================================================
server.port=8080


# =========================================================
# CONFIGURACIÓN BASE DE DATOS (H2)
# =========================================================
# Configuración de H2 en memoria
spring.datasource.url=jdbc:h2:mem:pedidosdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar la consola de H2 en el navegador para pruebas locales
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Mostrar las sentencias SQL en la consola para depurar
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


# =========================================================
# CONFIGURACIÓN DE AWS S3
# =========================================================
# Propiedades personalizadas
app.aws.access-key=${APP_AWS_ACCESS_KEY_ID:none}
app.aws.secret-key=${APP_AWS_SECRET_ACCESS_KEY:none}
app.aws.session-token=${APP_AWS_SESSION_TOKEN:none}
app.aws.region=us-east-1

# Nombre del Bucket S3
app.aws.s3.bucket=bucket-app-cloud


# ===================================================================
# CONFIGURACIÓN DE ALMACENAMIENTO TEMPORAL (Amazon EFS)
# ===================================================================
# En local se usará "target/efs".
# En producción (Docker/EC2), el pipeline le inyectará la ruta real "/app/efs"
app.efs.path=${APP_EFS_PATH:target/efs}


# ===================================================
# CONFIGURACIÓN DE SEGURIDAD E IDaaS (AZURE AD B2C)
# ===================================================
# URL del Issuer (Emisor del token)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://appcloudauth.b2clogin.com/tfp/8c788a54-6ef0-44a7-942c-0235a1fcfec7/b2c_1_auth/v2.0/

# URI del JWK Set (Claves Públicas de Verificación Criptográfica)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://appcloudauth.b2clogin.com/appcloudauth.onmicrosoft.com/b2c_1_auth/discovery/v2.0/keys


# ===================================================
# Modo debug para verificar el flujo de Spring Security
# ===================================================
logging.level.org.springframework.security=DEBUG


# ===================================================
# CONFIGURACIÓN DE RABBITMQ (MENSAJERÍA ASÍNCRONA)
# ===================================================
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASS}
# Si falla, lo rechaza y lo manda directo a la DLQ (Cola 2)
spring.rabbitmq.listener.simple.default-requeue-rejected=false
